export default [
    {
        id: 1,
        img: "/images/agatebluelace.jpg",
        title: "Agate Bluelace",
        description: "Agate Bluelace",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 2,
        img: "/images/agategreenonyx.jpg",
        title: "Agate Green Onyx",
        description: "Agate Green Onyx",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 3,
        img: "/images/amazonit.jpg",
        title: "Amazonit",
        description: "Amazonit",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 4,
        img: "/images/amberchampagn.jpg",
        title: "Amber Champagn",
        description: "Amber Champagn",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 5,
        img: "/images/ambercognac.jpg",
        title: "Amber Cognac",
        description: "Amber Cognac",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 6,
        img: "/images/amberofbaltic.jpg",
        title: "Amber Of Baltic",
        description: "Amber Of Baltic",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 7,
        img: "/images/amethyst.jpg",
        title: "Amethyst",
        description: "Amethyst",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 8,
        img: "/images/apatite.jpg",
        title: "Apatite",
        description: "Amethyst",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 9,
        img: "/images/aventurin.jpg",
        title: "Aventurin",
        description: "Amethyst",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 10,
        img: "/images/bullseye.jpg",
        title: "Bullseye",
        description: "Amethyst",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 11,
        img: "/images/carnelian.jpg",
        title: "Carnelian",
        description: "Amethyst",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 12,
        img: "/images/cateye.jpg",
        title: "Cateye",
        description: "Cateye",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 13,
        img: "/images/celestin.jpg",
        title: "Celestin",
        description: "Celestin",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 14,
        img: "/images/chakra.jpg",
        title: "Chakra",
        description: "Chakra",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 15,
        img: "/images/coral.jpg",
        title: "Coral",
        description: "Coral",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 16,
        img: "/images/fuchsite.jpg",
        title: "Fuchsite",
        description: "Fuchsite",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 17,
        img: "/images/galaxystone.jpg",
        title: "Galaxy Stone",
        description: "Galaxy Stone",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 18,
        img: "/images/garnet.jpg",
        title: "Garnet",
        description: "Garnet",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 19,
        img: "/images/hemimorphite.jpg",
        title: "Hemimorphite",
        description: "Garnet",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 20,
        img: "/images/hotpinkquartz.jpg",
        title: "Hot Pink Quartz.jpg",
        description: "Hot Pink Quartz",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 21,
        img: "/images/indianagate.jpg",
        title: "Indian Agate",
        description: "Indian Agate",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 22,
        img: "/images/jadeit.jpg",
        title: "Jadeit",
        description: "Jadeit",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 23,
        img: "/images/landscapejasper.jpg",
        title: "Landscape Jasper",
        description: "Landscape Jasper",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 24,
        img: "/images/lapislazuli.jpg",
        title: "Lapis Lazuli",
        description: "Lapis Lazuli",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 25,
        img: "/images/magnesit.jpg",
        title: "Magnesit",
        description: "Magnesit",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 26,
        img: "/images/malachite.jpg",
        title: "Malachite",
        description: "Malachite",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 27,
        img: "/images/mossagate.jpg",
        title: "Moss Agate",
        description: "Moss Agate",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 28,
        img: "/images/multicoloredturmalin.jpg",
        title: "Multicolored Turmalin",
        description: "Multicolored Turmalin",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 29,
        img: "/images/opalin.jpg",
        title: "Opalin",
        description: "Opalin",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 30,
        img: "/images/orangecalcit.jpg",
        title: "Orange Calcit",
        description: "Orange Calcit",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 31,
        img: "/images/prehnit.jpg",
        title: "Prehnit",
        description: "Prehnit",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 32,
        img: "/images/quartzcherry.jpg",
        title: "Quartz Cherry",
        description: "Quartz Cherry",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 33,
        img: "/images/quartztourmalin.jpg",
        title: "Quartz Tourmalin",
        description: "Quartz Tourmalin",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 34,
        img: "/images/redjasper.jpg",
        title: "Red Jasper",
        description: "Red Jasper",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 35,
        img: "/images/redobsidien.jpg",
        title: "Red Obsidien",
        description: "Red Obsidien",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 36,
        img: "/images/roseagate.jpg",
        title: "Rose Agate",
        description: "Rose Agate",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 37,
        img: "/images/rosehowlit.jpg",
        title: "Rose Howlit",
        description: "Rose Howlit",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 38,
        img: "/images/rosemoonstone.jpg",
        title: "Rose Moonstone",
        description: "Rose Moonstone",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 39,
        img: "/images/serpentin.jpg",
        title: "Serpentin",
        description: "Serpentin",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 40,
        img: "/images/snakejasper.jpg",
        title: "Snake Jasper",
        description: "Snake Jasper",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 41,
        img: "/images/snowflakeobsidian.jpg",
        title: "Snow Flake obsidian",
        description: "Snow Flake obsidian",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 42,
        img: "/images/sodalit.jpg",
        title: "Sodalit",
        description: "Sodalit",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 43,
        img: "/images/sunstone.jpg",
        title: "Sunstone",
        description: "Sunstone",
        price: "500 DA",
        postdate:"",
    },

    {
        id: 44,
        img: "/images/tigereye.jpg",
        title: "Tiger Eye",
        description: "Tiger Eye",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 45,
        img: "/images/unakit.jpg",
        title: "Unakit",
        description: "Unakit",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 46,
        img: "/images/whitehowlit.jpg",
        title: "White Howlit",
        description: "White Howlit",
        price: "500 DA",
        postdate:"",
    },
    {
        id: 47,
        img: "/images/yellowcateye.jpg",
        title: "Yellow Cat Eye",
        description: "Yellow Cat Eye",
        price: "500 DA",
        postdate:"",
    },
]